### ISSUE TITLE
Day 1 Content: Revamp the slides

### ISSUE THREAD

**Issue by harokevin** [Maigard/git-class#4]
Revamp the slides to pose the problem that git solves and how it solves it.

**Comment by harokevin** [comment]
I might also put in the quote about the goat sacrifice thing.

**Comment by harokevin** [comment]
A lot of people teach technical skills by giving a set of instructions in order and expecting the student will absorb the procedure, the concept, and what to expect all at once. It does not work that way. By teaching this strange set of instructions without meaning or mechanism explanations you’re basically saying “slaughter a goat on the full moon in an open field near running water and say some phrases in Latin and everything will be fine, but if you get any part of this wrong (some of which I might have forgotten to tell you about) everything will be irreparably ruined.”

eh, maybe not.

**Comment by harokevin** [comment]
These are two articles that showcase use cases for git that do not revolve around programming:
http://readwrite.com/2013/11/08/seven-ways-to-use-github-that-arent-coding/
https://www.wired.com/2013/09/github-for-anything/

Travel Log, Musical Composition, Recipes, Fonts, Journalists, Writing and blogging, Legal Documents

**Comment by harokevin** [comment]
I might also add a slide that highlights what others would define as git:
Erin: [Git] records and archives every step of the development process.

**Comment by Maigard** [comment]
Revamped to coincide with the try git online class in #11
